# Permalinks
permalink:           pretty

# Setup
title:               Fisher Moritzburke
tagline:             blog blog blog
url:                 http://snisher.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Fisher Moritzburke
  url:               https://github.com/snisher
  email:             fmoritzburke@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/snisher

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
